[caption = ""]

== Zextras Suite 3.1.11
Version 3.1.11 - May 17th, 2021

=== Auth
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* AUTH-202

4+|*Title:* Change the title to login page

4+|*Description:* You can now change the title to the login page.
|===

=== Backup
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* BCK-492

4+|*Title:* Restoration of particular Item on new account

4+|*Description:* Improvement in the working of restoration of appointments/calendar
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* BCK-494

4+|*Title:* Restore operation's speed improvements

4+|*Description:* The restore operation has been improved to increase its speed
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* BCK-496

4+|*Title:* Index suspended during restore operations

4+|*Description:* The Zimbra indexing is now temporarily disabled while performing restore operations such as the external restore and the restore on a new account to improve the restore performances.
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* BCK-514

4+|*Title:* LDAP dump created during daily Smart Scan

4+|*Description:* Now the daily Smart Scan operation will save a dump of the LDAP in the backup path.
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* BCK-518

4+|*Title:* Error message when missing blobs are found by the coherency check operation improved

4+|*Description:* The error message that the coherency check operation throws when a missing blob is found in the backup path has been clarified
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* BCK-519

4+|*Title:* Account/COS/domain configuration saved and restored

4+|*Description:* The Real-Time backup now saves account/COS/domain configuration too.
On restoring an account/COS/domain, it is now restored also the whole item configuration.
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* BCK-522

4+|*Title:* Improved error handling in coherency check on fixing backup

4+|*Description:* The handling of errors during a coherency check where the backup is being fixed has been improved, now if it is not possible to move files away from the backup path, an error will be thrown.
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* BCK-534

4+|*Title:* Improved debug logs on migrating the backup on third party store

4+|*Description:* The debug logs have been improved, now they log each remote call to the store, and more in detail, now every file upload to remote storage is logged for each folder.
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* BCK-540

4+|*Title:* Coherency check's backup fix operation fixed when missing Drive blobs

4+|*Description:* Fixed a bug that prevented the backup coherency check operation to properly fix the backup path when missing Drive's blobs are present
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* BCK-550

4+|*Title:* doUndelete operation now restores in the original folder by default

4+|*Description:* The restore inside the source folder is now the default behaviour of doUndelete command
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* BCK-577

4+|*Title:* doUndelete on restoring items in subfolders fixed

4+|*Description:* Fixed a bug that prevented the items in the subfolders to be properly restored inside its subfolder when restoring with the doUndelete command
|===

=== General
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* COR-496

4+|*Title:* Improvement in showing notifications empty list

4+|*Description:* When the notifications' list is empty, a status message is now shown to advise the admins to click the refresh button to update the list. A refresh button has also been added to refresh the list.
|===

=== Team
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-1489

4+|*Title:* Instant Meetings hosted on the owner's server

4+|*Description:* Now, an instant meeting is hosted on the server the user that creates the meeting resides on
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2467

4+|*Title:* Show separate stream for screen share

4+|*Description:* In a meeting, users can send two different streams: one for webcam and one for screen share
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2468

4+|*Title:* Autopin screen share

4+|*Description:* During an instant meeting, on sharing the screen the view automatically changes to cinema and the new screen share session is pinned when Video Server is used
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2544

4+|*Title:* History optimizations for groups and instant-meetings

4+|*Description:* Group invitation is now improved with the new option to allow users to show or hide the previous history of a group chat. Also in Instant meetings when a new user joins a meeting will not be able to see the previous history.
On the other hand, in spaces and channels, history will always be visible. Moreover, when a user leaves a conversation or the conversation is deleted, the clear conversation's data is removed.
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2554

4+|*Title:* Conversations messages clean up service has been implemented

4+|*Description:* A cleaning service has been implemented for messages that are no longer reachable and visible
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2709

4+|*Title:* Create space without participants

4+|*Description:* It is now possible for users to create spaces with no user
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2749

4+|*Title:* Instant meeting's modal window shown twice fixed

4+|*Description:* Instant meeting's modal windows will is no more shown twice on adding participants while creating an Instant meeting
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2761

4+|*Title:* Order of conversations on forward modal refactored

4+|*Description:* In the forward modal window, the conversations with cleared history were wrongly set at the top of the list.
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2777

4+|*Title:* Content-Type refactored in Team responses

4+|*Description:* Now all the HTTP responses but the 404 error will contain the Content-Type header so Team can be used in conjunction with "X-Content-Type-Options: nosniff" header.
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2787

4+|*Title:* Pin video icon during meeting fixed

4+|*Description:* The 'Pin video' action has been fixed and is now visible during a meeting both in grid and in cinema mode
|===
