[caption='']
== Zextras Suite 3.1.5
//Version 3.1.5 - November 30th, 2020

=== Auth
[cols="4*a", options="footer"]
|===
4+|Issue ID: AUTH-161

4+|*Title:* Mobile password must be exclusive for EAS

4+|*Description:* Fixed a bug that caused the account's password to be usable for EAS synchronization even if a Mobile Password was set.

4+|*Notes:* __Working as intended__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: AUTH-170

4+|*Title:* Improved "Domain configuration missing" notification

4+|*Description:* Auth's "Domain configuration missing" notification will now ignore domain alias and be sent at most once a day

4+|*Notes:* __Working as intended__
|===

=== Backup
[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-404

4+|*Title:* Fixed typo in smartscan email log

4+|*Description:* Added a missing hyphen in the "smarstcan completed" mail.

4+|*Notes:* __mail has all the needed hyphens__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-406

4+|*Title:* Backup volume on S3 creation fixed

4+|*Description:* Fixed a bug that prevented the backup volume to be correctly created if S3 credentals are passed to the command.

4+|*Notes:* __you no more need to create the bucket before setting the backup volume on S3__
|===

=== General
[cols="4*a", options="footer"]
|===
4+|Issue ID: COR-485

4+|*Title:* Fixed drive startup switch

4+|*Description:* Fixed an issue that would prevent an admin to disable drive at startup from the web admin console

4+|*Notes:* __The workaround zxsuite config server get `zmhostname` attribute isDriveEnabledOnStartup is no longer necessary__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: COR-504

4+|*Title:* CLI commands input validation for email addresses

4+|*Description:* Input validation has been added to CLI to warn the administrator when invalid email addresses are given.

4+|*Notes:* __More ease to understand CLI errors relative to email addresses__
|===

=== Docs
[cols="4*a", options="footer"]
|===
4+|Issue ID: DOCS-103

4+|*Title:* Sidebar hidden by default

4+|*Description:* The sidebar is now hidden by default in Docs so the interface is more clear.

4+|*Notes:* __the workspace is clearer now__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DOCS-105

4+|*Title:* Unauthenticated access to documents redirected

4+|*Description:* The unauthenticated access to documents is now redirected to the login page.

4+|*Notes:* __Unauthenticated accesses are now managed more efficiently__
|===

=== Drive
[cols="4*a", options="footer"]
|===
4+|Issue ID: DRIV-993

4+|*Title:* Fixed drive shares on distribution lists

4+|*Description:* Fixed an issue that would prevent drive items to be shared to distribution lists

4+|*Notes:* __Shares are correctly created__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DRIV-1002

4+|*Title:* Updated zimbraXverstion to 4.0.0

4+|*Description:* Updated zimbraXVersion value in the com_zimbra_drive_modern zimlet manifest

4+|*Notes:* __value has been updated__
|===

=== Mobile
[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-266

4+|*Title:* Follow-up flag improvement

4+|*Description:* Changed the logic of FlagType so mail sent via Exchange ActiveSync will not automatically have the follow-up flag.

4+|*Notes:* __sent emails no more have the follow-up flag set__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-276

4+|*Title:* All day events added to incorrect day fixed

4+|*Description:* Fixed a bug with the timezone that made the all day events created via Exchange ActiveSync to be added to the day before instead of the correct one on the webmail.

4+|*Notes:* __all day events created on the correct day__
|===

=== Powerstore
[cols="4*a", options="footer"]
|===
4+|Issue ID: PS-260

4+|*Title:* Deprecated drivesecondarystore value migration

4+|*Description:* Added the automatic creation of an hsm rule to implement what was once done using the parameter driveSecondaryStore

4+|*Notes:* __the driveSecondaryStore value is emptied, a mail sent to the admin account and if no hsm rule covers documents a new rule is created__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: PS-271

4+|*Title:* doCreateVolume command improved for centralized volumes

4+|*Description:* doCreateVolume command improved to give the administrator feedback when run.

4+|*Notes:* __now admins are notificated about the command execution__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: PS-275

4+|*Title:* Improved zxsuite online help

4+|*Description:* Added further examples when invoking a docheckblobs operation without parameters

4+|*Notes:* __useful information about docheckblobs parameter are now available__
|===

=== Team
[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1789

4+|*Title:* Added Team account status awareness

4+|*Description:* Team now verifies if the account status is "maintenance" and if not send or receive further messages for it.

4+|*Notes:* __account status is now honored__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1873

4+|*Title:* Added Instant message functions

4+|*Description:* Added Edit, Delete, Forward, Reply to to messages in conversations, groups, channels.

4+|*Notes:* __new feature implemented and functional__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1895

4+|*Title:* None

4+|*Description:* None

4+|*Notes:* _None_
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1938

4+|*Title:* [TSE] Ticket #36850, Case 01043426

4+|*Description:* User Report for issue TEAMS-1977

4+|*Notes:* _See TEAMS-1977_
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1970

4+|*Title:* TEAM loading screen Improvement

4+|*Description:* Improved TEAM opening screen, now an animation makes clear to the user that the application is loading

4+|*Notes:* __The new loading screen is functional__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1987

4+|*Title:* Fixed instant message text cleanup

4+|*Description:* Fixed an issue that would would not clean the instant message textbox of the minichat when the message was sent from the TEAM tab using the send button instead of enter

4+|*Notes:* __Instant message text cleanup is now functional even when using the send button__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-2013

4+|*Title:* Changed disable microphone behavior

4+|*Description:* Changed the disable microphone behavio, now only the local device will be muted instead of all user's devices

4+|*Notes:* __Disable microphone function now affects only one device__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-2019

4+|*Title:* Fixed minor graphic glitch

4+|*Description:* Fixed an issue on Modern that would cause a modal window to have buttons incorrectly placed when creating a new instant meeting while another one is already running

4+|*Notes:* __Modal window graphics look correct__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-2020

4+|*Title:* Fixed new instant meeting window buttons

4+|*Description:* Fixed an issue that would prevent all abort button not to work when creating a new instant meeting while another one is already running

4+|*Notes:* __All buttons inside the window are now responding__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-2026

4+|*Title:* Changed "Mute" behavior

4+|*Description:* The "Mute" button has been changed to "Mute for all"

4+|*Notes:* __Works as intented__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-2027

4+|*Title:* Meeting screenshare termination fix

4+|*Description:* Fixed an issue that would cause a screenshare to continue after closing the group/space/channel/instant meeting window

4+|*Notes:* __video stream is terminated as expected__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-2028

4+|*Title:* Screen sharing avatar behavior improvement

4+|*Description:* Improved the screen sharing avatar placement so that it no longer makes the screen sharing function difficult to use

4+|*Notes:* __avatar moved in a corner__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-2034

4+|*Title:* Fixed download concurrency issue

4+|*Description:* Fixed an issue that would cause video conferences and instant messaging to be unavailable for a few seconds while mail attachments are downloaded

4+|*Notes:* __attachment download no longer breaks instant messaging__
|===
