
[caption='']
== Zextras Suite 3.1.4
//Version 3.1.4 - November 2nd, 2020

=== Backup
[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-308

4+|*Title:* Account deletion logging improvement

4+|*Description:* Improved logging of account deletion operation that caused non-relevant lines to be logged when backup service is running but not initialized

4+|*Notes:* __log handling has been improved__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-366

4+|*Title:* External Restore backward compatibility improvement

4+|*Description:* Restoring data from backups made on very old releases now correctly import tag data

4+|*Notes:* __ it is now possible to migrate from old versions still in technical guidance__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-384

4+|*Title:* Added chat backup disable option

4+|*Description:* It is now possible to disable the chat backup from the scheduled operation

4+|*Notes:* __Chat database is not backed up when backupChatEnabled is set to false__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-385

4+|*Title:* Improved restore date handling

4+|*Description:* A more readable error is returned when a restore is attempted specifying a date from before the account was first backed up

4+|*Notes:* __The correct error is returned__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-386

4+|*Title:* Fixed doExport admin mail

4+|*Description:* Fixed the value of the backup export directory returned in the operation log mail received by the administrator

4+|*Notes:* __The backup path parameter is correctly returned__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-399

4+|*Title:* Added support for backup to external volume

4+|*Description:* It is now possible to use an external volume, for example an s3 bucket, as store for backup data

4+|*Notes:* __option is present and backup data is sent to the s3 bucket__
|===

=== General
[cols="4*a", options="footer"]
|===
4+|Issue ID: COR-417

4+|*Title:* Core page inaccessible with expired license fix

4+|*Description:* Fixed an issue that would make the core section of the zextras menu unusable with an expired license

4+|*Notes:* __it is now possible to upload a new license via web after the old one has expired__
|===

=== Docs
[cols="4*a", options="footer"]
|===
4+|Issue ID: DOCS-92

4+|*Title:* Docs codebase udate

4+|*Description:* Upgraded libreoffice component to version 4.2.6

4+|*Notes:* __the correct version is returned__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DOCS-99

4+|*Title:* Added Roboto font to Docs

4+|*Description:* Added the Roboto Font to Docs

4+|*Notes:* __Roboto font is listed__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DOCS-106

4+|*Title:* Fixed Safari compatibility issue

4+|*Description:* Fixed an issue that would prevent DOCS from opening, returning a security error

4+|*Notes:* __it is possible to use Docs on a Mac__
|===

=== Drive
[cols="4*a", options="footer"]
|===
4+|Issue ID: DRIV-83

4+|*Title:* Added Drive maintenance mode handling

4+|*Description:* Drive now no longer shows items shared by an account in maintenance mode

4+|*Notes:* __ drive correctly handles maintenance mode__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DRIV-933

4+|*Title:* Fixed Drive last version editor error

4+|*Description:* Fixed an issue that would cause an error to pop up if a user had a drive object last edited by another user that no longer exists

4+|*Notes:* __erro no longer presents itself__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DRIV-952

4+|*Title:* Improved deleted user handling in version

4+|*Description:* Improved Drive version list so that if a user that edited a file is deleted now "deleted user" is listed in the versions list

4+|*Notes:* __no error is returned__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DRIV-956

4+|*Title:* Fixed drive shared folder handling

4+|*Description:* Fixed an issue that would rend impossible to users to upload files to drive in a shared folder located on a different host

4+|*Notes:* __it is possible to upload files to different zimbra hosts__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DRIV-988

4+|*Title:* Drive public share Fix

4+|*Description:* Fixed an issue that would cause an error to be returned when opening the link of a public shared object

4+|*Notes:* __public shares appear to be working correctly__
|===

=== Mobile
[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-239

4+|*Title:* Appointment acceptation date/time fix

4+|*Description:* On accepting an appointment via Exchange ActiveSync, its date and time changed to the ones of the acceptation. Now this has been fixed.

4+|*Notes:* __works as expected__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-242

4+|*Title:* Added mobile custom zimbraId handling

4+|*Description:* Added support on Mobile for accounts having custon zimbraID uuid

4+|*Notes:* __it is possible to use accounts with custom zimbraId on mobile devices__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-248

4+|*Title:* Mobile password management removed from the Admin GUI

4+|*Description:* The mobile password management has been removed from the Admin GUI to be compliant with the new multiple mobile password management.

4+|*Notes:* __works as expected__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-254

4+|*Title:* Mobile calendar location parameters fix

4+|*Description:* Fixed an issue that would prevend calendar syncronization if a location was set and some fields were not compiled

4+|*Notes:* __locations configured with minimum data no longer cause device sync to fail__
|===
=== Backup
[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-308

4+|*Title:* Account deletion logging improvement

4+|*Description:* Improved logging of account deletion operation that caused non-relevant lines to be logged when backup service is running but not initialized

4+|*Notes:* __log handling has been improved__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-366

4+|*Title:* External Restore backward compatibility improvement

4+|*Description:* Restoring data from backups made on very old releases now correctly import tag data

4+|*Notes:* __ it is now possible to migrate from old versions still in technical guidance__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-384

4+|*Title:* Added chat backup disable option

4+|*Description:* It is now possible to disable the chat backup from the scheduled operation

4+|*Notes:* __Chat database is not backed up when backupChatEnabled is set to false__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-385

4+|*Title:* Improved restore date handling

4+|*Description:* A more readable error is returned when a restore is attempted specifying a date from before the account was first backed up

4+|*Notes:* __The correct error is returned__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-386

4+|*Title:* Fixed doExport admin mail

4+|*Description:* Fixed the value of the backup export directory returned in the operation log mail received by the administrator

4+|*Notes:* __The backup path parameter is correctly returned__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-399

4+|*Title:* Added support for backup to external volume

4+|*Description:* It is now possible to use an external volume, for example an s3 bucket, as store for backup data

4+|*Notes:* __option is present and backup data is sent to the s3 bucket__
|===

=== General
[cols="4*a", options="footer"]
|===
4+|Issue ID: COR-417

4+|*Title:* Core page inaccessible with expired license fix

4+|*Description:* Fixed an issue that would make the core section of the zextras menu unusable with an expired license

4+|*Notes:* __it is now possible to upload a new license via web after the old one has expired__
|===

// Version 3.0.11 - June 18th, 2020
_Release Date: June 18th, 2020_
=== Docs
[cols="4*a", options="footer"]
|===
4+|Issue ID: DOCS-92

4+|*Title:* Docs codebase udate

4+|*Description:* Upgraded libreoffice component to version 4.2.6

4+|*Notes:* __the correct version is returned__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DOCS-99

4+|*Title:* Added Roboto font to Docs

4+|*Description:* Added the Roboto Font to Docs

4+|*Notes:* __Roboto font is listed__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DOCS-106

4+|*Title:* Fixed Safari compatibility issue

4+|*Description:* Fixed an issue that would prevent DOCS from opening, returning a security error

4+|*Notes:* __it is possible to use Docs on a Mac__
|===

=== Drive
[cols="4*a", options="footer"]
|===
4+|Issue ID: DRIV-83

4+|*Title:* Added Drive maintenance mode handling

4+|*Description:* Drive now no longer shows items shared by an account in maintenance mode

4+|*Notes:* __ drive correctly handles maintenance mode__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DRIV-933

4+|*Title:* Fixed Drive last version editor error

4+|*Description:* Fixed an issue that would cause an error to pop up if a user had a drive object last edited by another user that no longer exists

4+|*Notes:* __erro no longer presents itself__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DRIV-952

4+|*Title:* Improved deleted user handling in version

4+|*Description:* Improved Drive version list so that if a user that edited a file is deleted now "deleted user" is listed in the versions list

4+|*Notes:* __no error is returned__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DRIV-956

4+|*Title:* Fixed drive shared folder handling

4+|*Description:* Fixed an issue that would rend impossible to users to upload files to drive in a shared folder located on a different host

4+|*Notes:* __it is possible to upload files to different zimbra hosts__
|===

=== Backup
[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-308

4+|*Title:* Account deletion logging improvement

4+|*Description:* Improved logging of account deletion operation that caused non-relevant lines to be logged when backup service is running but not initialized

4+|*Notes:* __log handling has been improved__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-366

4+|*Title:* External Restore backward compatibility improvement

4+|*Description:* Restoring data from backups made on very old releases now correctly import tag data

4+|*Notes:* __ it is now possible to migrate from old versions still in technical guidance__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-384

4+|*Title:* Added chat backup disable option

4+|*Description:* It is now possible to disable the chat backup from the scheduled operation

4+|*Notes:* __Chat database is not backed up when backupChatEnabled is set to false__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-385

4+|*Title:* Improved restore date handling

4+|*Description:* A more readable error is returned when a restore is attempted specifying a date from before the account was first backed up

4+|*Notes:* __The correct error is returned__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-386

4+|*Title:* Fixed doExport admin mail

4+|*Description:* Fixed the value of the backup export directory returned in the operation log mail received by the administrator

4+|*Notes:* __The backup path parameter is correctly returned__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: BCK-399

4+|*Title:* Added support for backup to external volume

4+|*Description:* It is now possible to use an external volume, for example an s3 bucket, as store for backup data

4+|*Notes:* __option is present and backup data is sent to the s3 bucket__
|===

=== General
[cols="4*a", options="footer"]
|===
4+|Issue ID: COR-417

4+|*Title:* Core page inaccessible with expired license fix

4+|*Description:* Fixed an issue that would make the core section of the zextras menu unusable with an expired license

4+|*Notes:* __it is now possible to upload a new license via web after the old one has expired__
|===

=== Docs
[cols="4*a", options="footer"]
|===
4+|Issue ID: DOCS-92

4+|*Title:* Docs codebase udate

4+|*Description:* Upgraded libreoffice component to version 4.2.6

4+|*Notes:* __the correct version is returned__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DOCS-99

4+|*Title:* Added Roboto font to Docs

4+|*Description:* Added the Roboto Font to Docs

4+|*Notes:* __Roboto font is listed__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DOCS-106

4+|*Title:* Fixed Safari compatibility issue

4+|*Description:* Fixed an issue that would prevent DOCS from opening, returning a security error

4+|*Notes:* __it is possible to use Docs on a Mac__
|===

=== Drive
[cols="4*a", options="footer"]
|===
4+|Issue ID: DRIV-83

4+|*Title:* Added Drive maintenance mode handling

4+|*Description:* Drive now no longer shows items shared by an account in maintenance mode

4+|*Notes:* __ drive correctly handles maintenance mode__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DRIV-933

4+|*Title:* Fixed Drive last version editor error

4+|*Description:* Fixed an issue that would cause an error to pop up if a user had a drive object last edited by another user that no longer exists

4+|*Notes:* __erro no longer presents itself__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DRIV-952

4+|*Title:* Improved deleted user handling in version

4+|*Description:* Improved Drive version list so that if a user that edited a file is deleted now "deleted user" is listed in the versions list

4+|*Notes:* __no error is returned__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DRIV-956

4+|*Title:* Fixed drive shared folder handling

4+|*Description:* Fixed an issue that would rend impossible to users to upload files to drive in a shared folder located on a different host

4+|*Notes:* __it is possible to upload files to different zimbra hosts__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DRIV-988

4+|*Title:* Drive public share Fix

4+|*Description:* Fixed an issue that would cause an error to be returned when opening the link of a public shared object

4+|*Notes:* __public shares appear to be working correctly__
|===

=== Mobile
[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-239

4+|*Title:* Appointment acceptation date/time fix

4+|*Description:* On accepting an appointment via Exchange ActiveSync, its date and time changed to the ones of the acceptation. Now this has been fixed.

4+|*Notes:* __works as expected__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-242

4+|*Title:* Added mobile custom zimbraId handling

4+|*Description:* Added support on Mobile for accounts having custon zimbraID uuid

4+|*Notes:* __it is possible to use accounts with custom zimbraId on mobile devices__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-248

4+|*Title:* Mobile password management removed from the Admin GUI

4+|*Description:* The mobile password management has been removed from the Admin GUI to be compliant with the new multiple mobile password management.

4+|*Notes:* __works as expected__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-254

4+|*Title:* Mobile calendar location parameters fix

4+|*Description:* Fixed an issue that would prevend calendar syncronization if a location was set and some fields were not compiled

4+|*Notes:* __locations configured with minimum data no longer cause device sync to fail__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-255

4+|*Title:* Mobile mail sender improvement

4+|*Description:* Improved behavior of mobile module that now predictably uses the main address as sender when personas are configured

4+|*Notes:* __it is possible to predict the sender address when personas are configured__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-273

4+|*Title:* Mobile device list Fix

4+|*Description:* Fixed an issue that would prevent the mobile section of the web admin console to show the list of mobile devices

4+|*Notes:* __a devices list is shown__
|===

=== Powerstore
[cols="4*a", options="footer"]
|===
4+|Issue ID: PS-263

4+|*Title:* S3 volume connections handling improvement

4+|*Description:* Improved s3 code to reduce the number of http(s) calls to a minimum

4+|*Notes:* __number of http calls appears to be lower__
|===

=== Team
[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1786

4+|*Title:* Webcam enabling on screen share ending fixed

4+|*Description:* Fixed the behaviour of the instant meeting that enabled the webcam after a screen sharing session during an instant meeting even if it was disabled before starting the screen share session.

4+|*Notes:* __now the instant meeting behaviour reflects the expectations of the users__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1819

4+|*Title:* Added status and avatar unset configuration

4+|*Description:* It is now possible to edit the user status and unset the avatar picture in the instant messaging settings

4+|*Notes:* __new options are available__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1835

4+|*Title:* Instant meeting creation Improvement

4+|*Description:* When a new instant meeting is created while another one is running all fields now appear empty

4+|*Notes:* __interface behaves as expected__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1869

4+|*Title:* Improved connection issue notification

4+|*Description:* A message is clearly shown when instant messaging is not possible due to connection issues

4+|*Notes:* __issue is clearly reported__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1930

4+|*Title:* Added Turkish translation to Team

4+|*Description:* Instant messaging interface now has Turkish translation

4+|*Notes:* __translation present__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: DRIV-988

4+|*Title:* Drive public share Fix

4+|*Description:* Fixed an issue that would cause an error to be returned when opening the link of a public shared object

4+|*Notes:* __public shares appear to be working correctly__
|===

=== Mobile
[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-239

4+|*Title:* Appointment acceptation date/time fix

4+|*Description:* On accepting an appointment via Exchange ActiveSync, its date and time changed to the ones of the acceptation. Now this has been fixed.

4+|*Notes:* __works as expected__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-242

4+|*Title:* Added mobile custom zimbraId handling

4+|*Description:* Added support on Mobile for accounts having custon zimbraID uuid

4+|*Notes:* __it is possible to use accounts with custom zimbraId on mobile devices__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-248

4+|*Title:* Mobile password management removed from the Admin GUI

4+|*Description:* The mobile password management has been removed from the Admin GUI to be compliant with the new multiple mobile password management.

4+|*Notes:* __works as expected__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-254

4+|*Title:* Mobile calendar location parameters fix

4+|*Description:* Fixed an issue that would prevend calendar syncronization if a location was set and some fields were not compiled

4+|*Notes:* __locations configured with minimum data no longer cause device sync to fail__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-255

4+|*Title:* Mobile mail sender improvement

4+|*Description:* Improved behavior of mobile module that now predictably uses the main address as sender when personas are configured

4+|*Notes:* __it is possible to predict the sender address when personas are configured__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-273

4+|*Title:* Mobile device list Fix

4+|*Description:* Fixed an issue that would prevent the mobile section of the web admin console to show the list of mobile devices

4+|*Notes:* __a devices list is shown__
|===

=== Powerstore
[cols="4*a", options="footer"]
|===
4+|Issue ID: PS-263

4+|*Title:* S3 volume connections handling improvement

4+|*Description:* Improved s3 code to reduce the number of http(s) calls to a minimum

4+|*Notes:* __number of http calls appears to be lower__
|===

=== Team
[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1786

4+|*Title:* Webcam enabling on screen share ending fixed

4+|*Description:* Fixed the behaviour of the instant meeting that enabled the webcam after a screen sharing session during an instant meeting even if it was disabled before starting the screen share session.

4+|*Notes:* __now the instant meeting behaviour reflects the expectations of the users__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1819

4+|*Title:* Added status and avatar unset configuration

4+|*Description:* It is now possible to edit the user status and unset the avatar picture in the instant messaging settings

4+|*Notes:* __new options are available__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1835

4+|*Title:* Instant meeting creation Improvement

4+|*Description:* When a new instant meeting is created while another one is running all fields now appear empty

4+|*Notes:* __interface behaves as expected__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1869

4+|*Title:* Improved connection issue notification

4+|*Description:* A message is clearly shown when instant messaging is not possible due to connection issues

4+|*Notes:* __issue is clearly reported__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1930

4+|*Title:* Added Turkish translation to Team

4+|*Description:* Instant messaging interface now has Turkish translation

4+|*Notes:* __translation present__
|===
[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-255

4+|*Title:* Mobile mail sender improvement

4+|*Description:* Improved behavior of mobile module that now predictably uses the main address as sender when personas are configured

4+|*Notes:* __it is possible to predict the sender address when personas are configured__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: MOB-273

4+|*Title:* Mobile device list Fix

4+|*Description:* Fixed an issue that would prevent the mobile section of the web admin console to show the list of mobile devices

4+|*Notes:* __a devices list is shown__
|===

=== Powerstore
[cols="4*a", options="footer"]
|===
4+|Issue ID: PS-263

4+|*Title:* S3 volume connections handling improvement

4+|*Description:* Improved s3 code to reduce the number of http(s) calls to a minimum

4+|*Notes:* __number of http calls appears to be lower__
|===

=== Team
[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1786

4+|*Title:* Webcam enabling on screen share ending fixed

4+|*Description:* Fixed the behaviour of the instant meeting that enabled the webcam after a screen sharing session during an instant meeting even if it was disabled before starting the screen share session.

4+|*Notes:* __now the instant meeting behaviour reflects the expectations of the users__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1819

4+|*Title:* Added status and avatar unset configuration

4+|*Description:* It is now possible to edit the user status and unset the avatar picture in the instant messaging settings

4+|*Notes:* __new options are available__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1835

4+|*Title:* Instant meeting creation Improvement

4+|*Description:* When a new instant meeting is created while another one is running all fields now appear empty

4+|*Notes:* __interface behaves as expected__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1869

4+|*Title:* Improved connection issue notification

4+|*Description:* A message is clearly shown when instant messaging is not possible due to connection issues

4+|*Notes:* __issue is clearly reported__
|===

[cols="4*a", options="footer"]
|===
4+|Issue ID: TEAMS-1930

4+|*Title:* Added Turkish translation to Team

4+|*Description:* Instant messaging interface now has Turkish translation

4+|*Notes:* __translation present__
|===
