[caption = ""]

= Zextras Suite Changelog - Release 3.2.0

Release Date 14th June, 2021

== Solved Escalations

Issue *MOB-348*, "All-day events scheduled one day before fix", solves ticket(s) 38976, 38926, 38594, 39068

Issue *PS-326*, "doMailboxMove required parameters", solves ticket(s) 38956

<<<
== Solved Issues

=== Auth
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* AUTH-237

4+|*Title:* Importing SAML configuration from the ISP

4+|*Description:* It is now possible to import SAML configuration directly from the ISP's configuration page.

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* AUTH-251

4+|*Title:* Improve the EAS code visualization

4+|*Description:* Now EAS code is showing properly with the font to PT Mono, generates the code without any issue (lower L), 1 (one), I (upper i) , O (upper o) and 0 (zero),

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* AUTH-254

4+|*Title:* 2FA enforcement for users

4+|*Description:* It is now possible for a user to enforce the two factor authentication for his account.

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* AUTH-257

4+|*Title:* enforce2FA CLI on wrong host

4+|*Description:* The enforce2FA CLI  command works if the target account has been created in any server, it works on all mailbox servers.

Note: custom:zx must be enabled on domain level_
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* AUTH-276

4+|*Title:* Pass a customer Domain as query in URL

4+|*Description:* If the customer domain is specified in the URL the login should work by entering the username without the domain.

|===

=== Backup
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* BCK-559

4+|*Title:* removal of  temp folder /mountpoint-restore

4+|*Description:* Temporary mountpoint removed after restoration of zxbackup.

|===

=== Mobile
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* MOB-348

4+|*Title:* All-day events scheduled one day before fix

4+|*Description:* A bug that caused the all-day events to be wrongly scheduled one day before the chosen date has been fixed.

|===

=== Powerstore
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* PS-326

4+|*Title:* doMailboxMove required parameters

4+|*Description:* If any missing parameter, an unknown error is thrown:

|===

=== Team
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2238

4+|*Title:* Forward action has been fixed

4+|*Description:* Now, users can forward text messages or files, stored on any server, to any single or group conversations.

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2241

4+|*Title:* Internal user can join instant meeting from URl

4+|*Description:* Internal user can join an external meeting

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2575

4+|*Title:* Groups moderators added

4+|*Description:* Now, users can also be moderators of groups

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2796

4+|*Title:* Auto swap main stream when a user is talking

4+|*Description:* The main tile in cinema mode changes automatically based on the person who is speaking

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2806

4+|*Title:* Calendar's attachments download broke Team's websocket connection

4+|*Description:* Calendar's attachments download broke WebSocket connection of Team.
Fixed an issue that would cause the drop of Team's WebSocket connection while calendar attachments are downloaded.

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2826

4+|*Title:* Limit signal sound to 10 seconds

4+|*Description:* Limit the free signal to 10 seconds on meetings

Working as intended._
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2827

4+|*Title:* Return to the previous meeting setup view when a screen stream ends

4+|*Description:* User returns to the previous meeting view mode when a share screen ends or to another screen share

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2846

4+|*Title:* Show talking users on carousel

4+|*Description:* On cinema mode, talking users that aren't in carousel change position to be shown.

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2856

4+|*Title:* Zextras logo at the end of instant meetings

4+|*Description:* "Powered by Zextras" on instant meeting pages that will be seen by external users has been added

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2871

4+|*Title:* Join's and switch inside meeting's tab sound

4+|*Description:* User A starts a meeting, changes the tab, user B joins the meeting, User A goes back to meeting view and the Meetingin sound is played wrongly.

|===
