[caption = ""]

= Zextras Suite Changelog - Release 3.3.0

Release Date July 12th, 2021

== Solved Issues

=== Auth
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* AUTH-242

4+|*Title:* SAML session invalidation on logout

4+|*Description:* If provided within the SAML configuration, the logout process now calls the SAML logout endpoint to invalidate the session.

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* AUTH-268

4+|*Title:* Fixed warn notification in the audit log file

4+|*Description:* Added the missing space in the authentication error notification in the audit.log file when a non-existent user logged in to the webmail from the Zextras Suite login page.

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* AUTH-289

4+|*Title:* unable to save the trusted device

4+|*Description:* Before this fix, if  two or more users log in using the same browser, there was an error saving the browser ID

|===

=== Backup
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* BCK-575

4+|*Title:* Handle not initialized backup on external restore.

4+|*Description:* Running an external restore without initializing the backup in the destination server now no longer generates errors.

|===

// [cols="4*a", options="footer"]
// |===
// 4+|*Issue ID:* BCK-590

// 4+|*Title:* Add an account restored Completed INFO to doExternalRestore logs

// 4+|*Description:* The account restoration logs now appear in phases and completion logs at the end.
// |===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* BCK-595

4+|*Title:* `Skip_domain_provisioning` on doExternalRestore operation

4+|*Description:* By default, the `skip_domain_provisioning` flag now set to `false` skips all the domain-based attributes on `doExternalRestore` operation. If users set `skip_domain_provisioning` to `true` and the account's domain is not present, the import fails.
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* BCK-597

4+|*Title:* External restore operation now restores shared contacts

4+|*Description:* Improved the external restore and the fixShares operations so they can restore shared contacts in groups too.
|===

=== General
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* COR-604

4+|*Title:* New config commands

4+|*Description:* With new configuration commands, users can now use `set`, `get`, and `unset` commands.

|===

=== Admin
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* DELEG-38

4+|*Title:* Now in Browse Logs window of Admin tab links to the new wiki

4+|*Description:* Updated Admin section "Browse Logs" link from the old wiki to the latest documentation page.

|===

=== Mobile
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* MOB-343

4+|*Title:* Users can now define the folders to exclude from Active Sync

4+|*Description:* Users can now exclude a folder, except any of the system folders, from Active Sync.
|===

=== Powerstore
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* PS-318

4+|*Title:* Indexing delayed on endpoints unavailability

4+|*Description:* When the indexing endpoints are unavailable, the indexing is delayed, and the failure count is updated.

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* PS-320

4+|*Title:* Notify the admin if the indexing extraction tool's endpoint is  unavailable

4+|*Description:* A notification now informs the admins when none of the indexing extraction's endpoints is unavailable.

|===

=== Team
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2559

4+|*Title:* Improved video server command's help output

4+|*Description:* When users run the video server command without parameters, a list of options with descriptions appears as output instead of an error.
|===

// [cols="4*a", options="footer"]
// |===
// 4+|*Issue ID:* TEAMS-2690

// 4+|*Title:* Margin at the end of a conversation removed

// 4+|*Description:* In Zextras Teams, each conversation had an area at the end of the chat that users could scroll further. The margin at the end of a conversation no longer appears.
// |===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2842

4+|*Title:* Conversation scroll on new messages fixed

4+|*Description:* Fixed a bug that prevented conversations from scrolling on receiving new messages while the _is writing_ bubble is present.
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2850

4+|*Title:* A notification now informs the users when someone mutes them.

4+|*Description:* Users now receive a notification when someone mutes them. This notification remains as an alert until users acknowledge it.

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2889

4+|*Title:* Limited "add member" functionality to groups only to moderators.

4+|*Description:* With API version 14, the "add member" functionality is limited to groups and restricted only to moderators.

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2931

4+|*Title:* "MuteForAll" button has been limited only to moderators

4+|*Description:* Only moderators can now mute other people in a group, space, or channel meeting.

|===