= Zextras Suite Changelog - Release 3.6.0

Release Date October 4th, 2021

== Solved Issues

=== Auth
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* AUTH-300

4+|*Title:* OTP Label is now customizable

4+|*Description:* Users can now edit labels of newly generated TOTPs.
|===

=== Drive
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* DRIV-1207

4+|*Title:* Window title now reads Drive in place of Zimbra Drive.

4+|*Description:* The title of Drive window for external users has changed to "Drive".
|===

=== Powerstore
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* PS-325

4+|*Title:* Enhanced Mailbox move speed

4+|*Description:* Optimizations to the `MailboxMove` command operation now speeds up the operation thereby reducing the time taken.
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* PS-342

4+|*Title:* Tika indexing exceptions management enhanced

4+|*Description:* Documents that raise 204 (no content) and 422 (unprocessable entity) HTTP codes as a result of Tika parsing are no longer re-tried and a log is reported in the `mailbox.log` file.
|===

=== Team
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2317

4+|*Title:* Optimized Team performance to address lag

4+|*Description:* Zextras Team now performs better and no longer lags after prolonged usage.
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2440

4+|*Title:* Updated logs for ChatAutoCleanup procedure

4+|*Description:* The ChatAutoCleanup procedure now no longer shows incomplete logs.
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-2510

4+|*Title:* Teams no longer saves mute status of exiting users

4+|*Description:* Users' mute status is no longer remembered by Teams and users returning to an ongoing conversation are not muted -- irrespective of their mute status when exiting.
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-3034

4+|*Title:* Improved Team file download

4+|*Description:* Users sometimes faces issues when downloading files sent by other users. The download of a file from one-to-one chat now no longer suffers casual failures due to buffer issues.
|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-3108

4+|*Title:* Fixed a paste issue on Chrome versions higher than 91.

4+|*Description:* Fixed issue where users, on chrome version higher than 92, experienced issues when pasting text in a conversation.
|===
