= Zextras Suite Changelog - Release 3.7.0

Release Date November 2nd, 2021

== Solved Issues

=== Auth
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* AUTH-314

4+|*Title:* Password change with custom zimbraAuthMech

4+|*Description:* It is now possible for the users to change their password after admins have enabled the custom:zx zimbraAuthMech

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* AUTH-320

4+|*Title:* New tab for Auth zimlet

4+|*Description:* By clicking on the Zextras Auth zimlet, a new Auth tab will be opened resulting in a clearer interface for the users.

|===

=== Backup
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* BCK-589

4+|*Title:* Moved mailboxes now marked as deleted

4+|*Description:* The doPurgeMailboxes operation now marks as deleted mailboxes the ones that are moved to other servers. This makes the Backup purge operation clean the data left after by the move operations too.

|===

=== General
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* COR-639

4+|*Title:* Text selection and contextual menu in administration console fixed

4+|*Description:* Fixed a bug that caused the text selection and the contextual menu in the Zimbra administration console not to work properly.

|===

[cols="4*a", options="footer"]
|===
4+|*Issue ID:* COR-644

4+|*Title:* Temporary link for 2FA users login

4+|*Description:* In order to allow users with 2FA enabled to log in, Admin generates a preauth link from the admin console and can send the link to the user, that will be able to access the webmail

|===

=== Mobile
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* MOB-357

4+|*Title:* Bug with PARTSTAT field on appointment invitation fixed

4+|*Description:* Fixed a bug that caused the PARTSTAT field of an invitation to be wrongly set as NEED-ACTION on accepting one appointment via Exchange ActiveSync. This bug caused the appointment not to be shown via CalDAV.

|===

=== Team
[cols="4*a", options="footer"]
|===
4+|*Issue ID:* TEAMS-3215

4+|*Title:* Accessibility improved in Team

4+|*Description:* Now every icon in Team has an alternative text, a title and a label to improve accessibility.

|===

